/// Supplies flag values to a container tree.
///
/// A ``SignalTower`` is the production implementation; tests and previews can supply
/// their own without pulling in any storage.
public protocol FlagLookup: AnyObject, Sendable {

    /// How property-name paths become the keys this lookup stores values under.
    var keyEncoding: KeyEncoding { get }

    /// The stored value for a key, or `nil` if no source provides one.
    func box(for key: FlagKey) -> FlagValueBox?
}

/// A type that groups flags, and optionally further containers.
///
/// Conformance is generated by the `@FlagContainer` macro. Both requirements are
/// underscored because they are call sites for generated code, not for you.
public protocol FlagContainer: Sendable {

    /// Builds the container, wiring every flag beneath it to `_lookup` and rooting its
    /// keys at `_keyPrefix`.
    init(_lookup: any FlagLookup, _keyPrefix: FlagKeyPath)

    /// The container's shape, described without needing an instance.
    ///
    /// This is what lets a host publish its schema — and a companion app render it —
    /// with no runtime reflection anywhere.
    static var flagDescriptors: [FlagSchemaNode] { get }
}
