import Combine

/// Supplies flag values to a container tree.
///
/// A ``FlagPole`` is the production implementation; tests and previews can supply
/// their own, implementing only ``box(for:as:)`` and ``keyEncoding``.
public protocol FlagLookup: AnyObject, Sendable {

    /// How property-name paths become the keys this lookup stores values under.
    var keyEncoding: KeyEncoding { get }

    /// The value for a key, or `nil` if nothing supplies one.
    ///
    /// `type` is the flag's declared type, so a lookup backed by a loosely typed
    /// medium can decode exactly rather than guess.
    func box(for key: FlagKey, as type: FlagValueType) -> FlagValueBox?

    /// Emits whenever the value for `key` may have changed.
    func changePublisher(for key: FlagKey) -> AnyPublisher<Void, Never>

    /// Stores an override, or removes it when `box` is `nil`.
    func setOverride(_ box: FlagValueBox?, for key: FlagKey) throws
}

extension FlagLookup {

    /// A lookup with nothing to observe never emits.
    public func changePublisher(for key: FlagKey) -> AnyPublisher<Void, Never> {
        Empty(completeImmediately: false).eraseToAnyPublisher()
    }

    /// A read-only lookup rejects writes.
    public func setOverride(_ box: FlagValueBox?, for key: FlagKey) throws {
        throw FlagError.noMutableSource
    }
}

/// A type that groups flags, and optionally further containers.
///
/// Conformance is generated by the `@FlagContainer` macro. Both requirements are
/// underscored because they are call sites for generated code, not for you.
public protocol FlagContainer: Sendable {

    /// Builds the container, wiring every flag beneath it to `_lookup` and rooting its
    /// keys at `_keyPrefix`.
    init(_lookup: any FlagLookup, _keyPrefix: FlagKeyPath)

    /// The container's shape, described without needing an instance.
    ///
    /// This is what lets a host publish its schema — and a companion app render it —
    /// with no runtime reflection anywhere.
    static var flagDescriptors: [FlagSchemaNode] { get }
}
